version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: psql_database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: psql_database
      POSTGRES_USER: ludwig
      POSTGRES_PASSWORD: q1w2e3r4
    volumes:
      - postgres-data:/var/lib/postgresql/data

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rest-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/psql_database
      SPRING_DATASOURCE_USERNAME: ludwig
      SPRING_DATASOURCE_PASSWORD: q1w2e3r4

volumes:
  postgres-data:
