spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: false
        acks: all
        batch-size: 32768
        linger-ms: 20
        retries: 2147483647
        enable-idempotence: true
        max-in-flight-requests-per-connection: 3
      compression-type: snappy




kafka:
  topic: batch-filter-consum-reading-garant
  partitions: 1
  replication-factor: 1

