http.host: 0.0.0.0

node.name: logstash

xpack.monitoring.enabled: false
config.debug: false
config.reload.automatic: true
config.reload.interval: 20
log.level: info
log.format: json
path.logs: /usr/share/logstash/logs