server:
  port: 8081

spring:
  application:
    name: topics
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: topics-reactive-rest-api
            scope: openid, profile, email
            authorization-grant-type: authorization_code
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_PROVIDER_URI:http://localhost:8282/realms/tinkoff-course/protocol/openid-connect/certs}


  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://root:root@localhost:7017/topics?authSource=admin
      auto-index-creation: true


logging:
  level:
    ru: trace
    org:
      springframework:
        web:
          client:
            RestTemplate: debug
          servlet:
            DispatcherServlet: debug
            handler: debug
            filter: debug
        security:
          web: debug
        data:
          mongodb:
            core: trace
        cache: trace
    com: info
